"use client";

import {useState} from "react";
import {merchants} from "@/lib/seed";
import {missing} from "@/lib/engine";
import type {AppState,Price} from "@/lib/types";

const money=(n:number)=>new Intl.NumberFormat("fr-CA",{style:"currency",currency:"CAD"}).format(n);
type Replacement={url:string;price:number|"";quantity:number|""};
const emptyReplacement:Replacement={url:"",price:"",quantity:1};

export default function CandidatePrices({state,setState}:{state:AppState;setState:React.Dispatch<React.SetStateAction<AppState>>}){
 const [replacements,setReplacements]=useState<Record<string,Replacement>>({});
 const candidates=state.prices.filter(p=>{const item=state.items.find(i=>i.id===p.itemId);if(p.matchStatus!=="candidate"||!item)return false;const needed=missing(item,state.inventory,state.items);if(needed<=0)return false;const proposedCost=Math.ceil(needed/Math.max(1,p.packageQuantity))*p.packagePrice;const cheaperConfirmed=state.prices.some(other=>other.itemId===p.itemId&&other.matchStatus==="verified"&&other.merchantId!==p.merchantId&&Math.ceil(needed/Math.max(1,other.packageQuantity))*other.packagePrice<proposedCost);return !cheaperConfirmed;}).filter((p,index,all)=>{const item=state.items.find(i=>i.id===p.itemId);const needed=item?missing(item,state.inventory,state.items):0;const cost=Math.ceil(needed/Math.max(1,p.packageQuantity))*p.packagePrice;const hasCheaper=all.some((other,otherIndex)=>{if(otherIndex===index||other.itemId!==p.itemId)return false;const otherCost=Math.ceil(needed/Math.max(1,other.packageQuantity))*other.packagePrice;return otherCost<cost||(otherCost===cost&&otherIndex<index);});const duplicate=all.findIndex(other=>{const otherItem=state.items.find(i=>i.id===other.itemId);return otherItem?.name===item?.name&&other.productName===p.productName&&other.merchantId===p.merchantId&&other.packagePrice===p.packagePrice&&other.packageQuantity===p.packageQuantity;})!==index;return !hasCheaper&&!duplicate;});
 const key=(price:Price)=>`${price.itemId}|${price.merchantId}`;
 const replacementFor=(price:Price)=>replacements[key(price)]??emptyReplacement;
 const changeReplacement=(price:Price,patch:Partial<Replacement>)=>setReplacements(current=>({...current,[key(price)]:{...replacementFor(price),...patch}}));
 const decide=(price:Price,accepted:boolean)=>setState(s=>({...s,prices:s.prices.map(p=>p.itemId===price.itemId&&p.merchantId===price.merchantId?{...p,matchStatus:accepted?"verified":"rejected",verifiedAt:accepted?new Date().toISOString():undefined}:p)}));
 const replaceWithLink=(price:Price,itemName:string)=>{
  const replacement=replacementFor(price);
  if(!replacement.url.startsWith("http")||typeof replacement.price!=="number"||replacement.price<=0||typeof replacement.quantity!=="number"||replacement.quantity<1)return;
  setState(s=>({...s,prices:s.prices.map(p=>p.itemId===price.itemId&&p.merchantId===price.merchantId?{...p,sourceUrl:replacement.url,packagePrice:replacement.price as number,packageQuantity:replacement.quantity as number,productName:`${itemName} — lien fourni par vous`,matchStatus:"verified",verifiedAt:new Date().toISOString(),matchNote:undefined}:p)}));
 };
 if(!candidates.length)return null;
 return <><h2>Produits incertains</h2><div className="notice">Vous n’avez pas à tous les vérifier. L’optimisation les compare et vous demandera seulement de confirmer ceux qui font partie du plan le moins cher.</div>{candidates.map(p=>{const x=state.items.find(i=>i.id===p.itemId),m=merchants.find(x=>x.id===p.merchantId),replacement=replacementFor(p),valid=replacement.url.startsWith("http")&&typeof replacement.price==="number"&&replacement.price>0&&typeof replacement.quantity==="number"&&replacement.quantity>=1;return <div className="card" key={key(p)}><strong>{x?.name}{x?.color?` — ${x.color}`:""}</strong><div className="muted">Demandé : {[x?.format,x?.requirements].filter(Boolean).join(" · ")||"format courant"}</div><div style={{marginTop:10}}><b>Proposé chez {m?.name} :</b> {p.productName}</div><div>{money(p.packagePrice)} pour {p.packageQuantity}</div>{p.matchNote&&<div className="notice" style={{marginTop:10}}>{p.matchNote}</div>}<div className="row" style={{marginTop:12}}><button onClick={()=>decide(p,true)}>Compatible — comparer</button><button className="ghost" onClick={()=>decide(p,false)}>Non compatible</button>{p.sourceUrl&&<a href={p.sourceUrl} target="_blank" rel="noreferrer">Voir le produit</a>}</div><div className="notice" style={{marginTop:14}}><strong>J’ai trouvé le bon produit</strong><div className="muted" style={{marginTop:4}}>Collez son lien, puis indiquez le prix et la quantité du paquet. Il remplacera cette proposition dans l’optimisation.</div><div className="field" style={{marginTop:10}}><label>Lien du produit</label><input type="url" inputMode="url" placeholder="https://…" value={replacement.url} onChange={e=>changeReplacement(p,{url:e.target.value})}/></div><div className="grid"><div className="field"><label>Prix du paquet</label><input type="number" inputMode="decimal" min="0" step="0.01" placeholder="0,00" value={replacement.price} onChange={e=>changeReplacement(p,{price:e.target.value===""?"":Number(e.target.value)})}/></div><div className="field"><label>Quantité dans le paquet</label><input type="number" inputMode="numeric" min="1" step="1" value={replacement.quantity} onChange={e=>changeReplacement(p,{quantity:e.target.value===""?"":Number(e.target.value)})}/></div></div><button disabled={!valid} onClick={()=>replaceWithLink(p,x?.name??"Produit")}>Remplacer par ce produit</button></div></div>})}</>;
}
