"use client";
import {useEffect} from "react";
import {merchants,initialState} from "@/lib/seed";
import type {AppState,MerchantId,MerchantSetting} from "@/lib/types";
const locators:Record<MerchantId,string>={"jean-coutu":"https://www.jeancoutu.com/localisateur-succursale/","bureau-en-gros":"https://stores.staples.ca/","commande-scolaire":"https://commandescolaire.com/nous-joindre/"};
export default function MerchantSettings({state,setState}:{state:AppState;setState:React.Dispatch<React.SetStateAction<AppState>>}){
 const defaults=initialState.merchantSettings||[];
 const settings=merchants.map(m=>{const saved=(state.merchantSettings||[]).find(x=>x.merchantId===m.id),base=defaults.find(x=>x.merchantId===m.id)!,legacy=saved?.mode==="store"||saved?.mode==="online";return legacy?{...base,branch:saved?.branch,postalCode:saved?.postalCode}:{...base,...saved} as MerchantSetting});
 useEffect(()=>{if((state.merchantSettings||[]).some(x=>x.mode==="store"||x.mode==="online"))setState(s=>({...s,merchantSettings:settings}))},[]);
 const change=(id:MerchantId,patch:Partial<MerchantSetting>)=>setState(s=>({...s,merchantSettings:settings.map(x=>x.merchantId===id?{...x,...patch}:x)}));
 return <><h2>Comment voulez-vous acheter?</h2><div className="notice">Choisissez « Optimise pour moi » pour laisser l’application comparer la livraison, le ramassage et le déplacement en magasin.</div>{merchants.map(m=>{const x=settings.find(s=>s.merchantId===m.id)!;return <div className="card" key={m.id}><strong>{m.name}</strong><div className="field"><label>Mode d’achat</label><select value={x.mode} onChange={e=>change(m.id,{mode:e.target.value as MerchantSetting["mode"]})}><option value="auto">Optimise pour moi — choisir le moins cher</option><option value="shop">Magasinage en personne</option><option value="pickup">Commande en ligne — ramassage en magasin</option><option value="delivery">Commande en ligne — livraison à domicile</option></select></div>{x.mode!=="shop"&&<div className="field"><label>Code postal</label><input inputMode="text" placeholder="Ex. J3H 2Y5" value={x.postalCode||""} onChange={e=>change(m.id,{postalCode:e.target.value.toUpperCase()})}/></div>}{x.mode!=="delivery"&&<><div className="field"><label>Succursale préférée</label><input placeholder="Nom ou adresse de la succursale" value={x.branch||""} onChange={e=>change(m.id,{branch:e.target.value})}/></div><a href={locators[m.id]} target="_blank" rel="noreferrer">Trouver une succursale près de mon code postal</a></>}{(x.mode==="pickup"||x.mode==="auto")&&<div className="field"><label>Frais de préparation ou ramassage</label><input type="number" min="0" step=".01" value={x.pickupFee||0} onChange={e=>change(m.id,{pickupFee:+e.target.value})}/></div>}{(x.mode==="delivery"||x.mode==="auto")&&<div className="grid"><div className="field"><label>Frais de livraison estimés</label><input type="number" min="0" step=".01" value={x.shippingFee} onChange={e=>change(m.id,{shippingFee:+e.target.value})}/></div><div className="field"><label>Livraison gratuite dès</label><input type="number" min="0" step=".01" value={x.freeShippingThreshold||0} onChange={e=>change(m.id,{freeShippingThreshold:+e.target.value||undefined})}/></div></div>}{(x.mode==="auto"||x.mode==="shop"||x.mode==="pickup")&&<div className="field"><label>Coût estimé du déplacement (essence et temps)</label><input type="number" min="0" step=".01" value={x.travelCost||0} onChange={e=>change(m.id,{travelCost:+e.target.value})}/></div>}{x.feeNote&&<div className="notice" style={{marginTop:12}}>{x.feeNote}</div>}</div>})}</>;
}
