"use client";
import {useEffect,useState} from "react";
import {MapPin} from "lucide-react";
import {merchants,initialState} from "@/lib/seed";
import type {AppState,MerchantId,MerchantSetting} from "@/lib/types";
type Branch={name:string;lat:number;lon:number};
type Suggestions=Partial<Record<MerchantId,Branch[]>>;
export default function MerchantSettings({state,setState}:{state:AppState;setState:React.Dispatch<React.SetStateAction<AppState>>}){
 const defaults=initialState.merchantSettings||[],[suggestions,setSuggestions]=useState<Suggestions>({}),[searching,setSearching]=useState(false),[searchMessage,setSearchMessage]=useState("");
 const settings=merchants.map(m=>{const saved=(state.merchantSettings||[]).find(x=>x.merchantId===m.id),base=defaults.find(x=>x.merchantId===m.id)!,legacy=saved?.mode==="store"||saved?.mode==="online";return legacy?{...base,branch:saved?.branch}:{...base,...saved} as MerchantSetting});
 useEffect(()=>{if((state.merchantSettings||[]).some(x=>x.mode==="store"||x.mode==="online"))setState(s=>({...s,merchantSettings:settings}))},[]);
 const change=(id:MerchantId,patch:Partial<MerchantSetting>)=>setState(s=>({...s,merchantSettings:settings.map(x=>x.merchantId===id?{...x,...patch}:x)}));
 const findBranches=async()=>{const postal=(state.postalCode||"").replace(/\s/g,"");if(postal.length!==6){setSearchMessage("Inscrivez un code postal canadien complet.");return}setSearching(true);setSearchMessage("");try{const res=await fetch(`/api/branches?postalCode=${encodeURIComponent(postal)}`),data=await res.json();if(!res.ok)throw new Error(data.error);setSuggestions(data);setSearchMessage("Choisissez une succursale parmi les résultats.")}catch(e){setSearchMessage(e instanceof Error?e.message:"Recherche indisponible.")}finally{setSearching(false)}};
 return <><h2>Comment voulez-vous acheter?</h2><div className="notice">Un seul code postal est utilisé pour tous les magasins. L’application propose jusqu’à trois succursales proches et compare les frais monétaires, sans estimer votre déplacement.</div><div className="card"><div className="field"><label>Votre code postal</label><input inputMode="text" placeholder="Ex. J3H 2Y5" value={state.postalCode||""} onChange={e=>setState(s=>({...s,postalCode:e.target.value.toUpperCase()}))}/></div><button className="wide secondary" onClick={findBranches} disabled={searching}><MapPin size={17}/>{searching?"Recherche…":"Proposer 3 succursales autour"}</button>{searchMessage&&<p className="muted">{searchMessage}</p>}</div>{merchants.map(m=>{const x=settings.find(s=>s.merchantId===m.id)!,near=suggestions[m.id]||[],hasBranches=m.id==="jean-coutu"||m.id==="bureau-en-gros";return <div className="card" key={m.id}><strong>{m.name}</strong><div className="field"><label>Mode d’achat</label><select value={x.mode} onChange={e=>change(m.id,{mode:e.target.value as MerchantSetting["mode"]})}><option value="auto">Optimise pour moi — choisir le moins cher</option>{m.id!=="amazon"&&<><option value="shop">Magasinage en personne</option><option value="pickup">Commande en ligne — ramassage en magasin</option></>}<option value="delivery">{m.id==="amazon"?"Amazon Prime — livraison gratuite":"Commande en ligne — livraison à domicile"}</option></select></div>{hasBranches&&near.length>0&&<div className="field"><label>Trois succursales proposées</label>{near.map((b,i)=><button className={x.branch===b.name?"wide":"wide ghost"} style={{marginTop:7}} key={b.name} onClick={()=>change(m.id,{branch:b.name})}>{i+1}. {b.name}</button>)}</div>}{hasBranches&&<div className="field"><label>Succursale choisie</label><input placeholder="Choisissez un résultat ou inscrivez une adresse" value={x.branch||""} onChange={e=>change(m.id,{branch:e.target.value})}/></div>}{(x.mode==="pickup"||x.mode==="auto")&&hasBranches&&<div className="field"><label>Frais de ramassage</label><input type="number" min="0" step=".01" value={x.pickupFee||0} onChange={e=>change(m.id,{pickupFee:+e.target.value})}/></div>}{(x.mode==="delivery"||x.mode==="auto")&&<div className="grid"><div className="field"><label>Frais de livraison</label><input type="number" min="0" step=".01" value={x.shippingFee} onChange={e=>change(m.id,{shippingFee:+e.target.value})}/></div><div className="field"><label>Gratuite dès</label><input type="number" min="0" step=".01" value={x.freeShippingThreshold||0} onChange={e=>change(m.id,{freeShippingThreshold:+e.target.value||undefined})}/></div></div>}{x.feeNote&&<div className="notice" style={{marginTop:12}}>{x.feeNote}</div>}</div>})}</>;
}
