"use client";
import {useState} from "react";
import CandidatePrices from "@/components/candidate-prices";
import {merchants} from "@/lib/seed";
import type {AppState,MerchantId,Price} from "@/lib/types";
const money=(n:number)=>new Intl.NumberFormat("fr-CA",{style:"currency",currency:"CAD"}).format(n);
export default function VerifiedPrices({state,setState}:{state:AppState;setState:React.Dispatch<React.SetStateAction<AppState>>}){
 const [draft,setDraft]=useState<Price>({itemId:state.items[0]?.id||"",merchantId:"jean-coutu",packagePrice:0,packageQuantity:1,available:true});
 const save=()=>{if(!draft.itemId||draft.packagePrice<=0||!draft.sourceUrl)return;const verified={...draft,verifiedAt:new Date().toISOString(),matchStatus:"verified" as const};setState(s=>({...s,prices:[...s.prices.filter(p=>!(p.itemId===verified.itemId&&p.merchantId===verified.merchantId)),verified]}))};
 const verified=state.prices.filter(p=>p.verifiedAt&&p.matchStatus!=="rejected");
 return <><CandidatePrices state={state} setState={setState}/><h2>Prix vérifiés</h2><div className="card"><div className="notice">Un prix entre dans le calcul seulement avec un lien vers le produit et une date de vérification.</div><div className="field"><label>Article</label><select value={draft.itemId} onChange={e=>setDraft({...draft,itemId:e.target.value})}>{state.items.map(x=><option value={x.id} key={x.id}>{x.level} · {x.name}{x.color?` · ${x.color}`:""}</option>)}</select></div><div className="field"><label>Magasin</label><select value={draft.merchantId} onChange={e=>setDraft({...draft,merchantId:e.target.value as MerchantId})}>{merchants.map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select></div><div className="grid"><div className="field"><label>Prix du paquet (CAD)</label><input type="number" min="0" step=".01" value={draft.packagePrice} onChange={e=>setDraft({...draft,packagePrice:+e.target.value})}/></div><div className="field"><label>Quantité dans le paquet</label><input type="number" min="1" value={draft.packageQuantity} onChange={e=>setDraft({...draft,packageQuantity:Math.max(1,+e.target.value)})}/></div></div><div className="field"><label>Nom exact du produit</label><input value={draft.productName||""} onChange={e=>setDraft({...draft,productName:e.target.value})}/></div><div className="field"><label>Lien de la page du magasin</label><input type="url" placeholder="https://…" value={draft.sourceUrl||""} onChange={e=>setDraft({...draft,sourceUrl:e.target.value})}/></div><div className="field"><label>Promotion affichée</label><input placeholder="Ex. 2 pour 5 $" value={draft.promotionLabel||""} onChange={e=>setDraft({...draft,promotionLabel:e.target.value})}/></div><button className="wide" disabled={!draft.itemId||draft.packagePrice<=0||!draft.sourceUrl} onClick={save}>Enregistrer ce prix vérifié</button></div>{verified.map(p=>{const x=state.items.find(i=>i.id===p.itemId),m=merchants.find(x=>x.id===p.merchantId);return <div className="card" key={p.itemId+p.merchantId}><strong>{x?.name} · {m?.name}</strong><div>{money(p.packagePrice)} pour {p.packageQuantity}</div><div className="muted">Vérifié le {new Date(p.verifiedAt!).toLocaleDateString("fr-CA")}{p.promotionLabel?` · ${p.promotionLabel}`:""}</div>{p.sourceUrl&&<a href={p.sourceUrl} target="_blank" rel="noreferrer">Voir la source</a>}</div>})}</>;
}
