import {AppState,Inventory,MerchantId,PlanLine,Strategy,Supply} from "./types";
export function inventoryUsed(item:Supply,inventory:Inventory[]){return inventory.filter(x=>x.name.toLowerCase()===item.name.toLowerCase()&&(!item.color||x.color?.toLowerCase()===item.color.toLowerCase())&&(!item.format||x.format?.toLowerCase()===item.format.toLowerCase())).reduce((n,x)=>n+x.quantity,0)}
export function missing(item:Supply,inventory:Inventory[],allItems:Supply[]=[item]){if(["Acheté","Commandé","J’en ai déjà"].includes(item.status))return 0;const compatible=(x:Supply)=>x.name.toLowerCase()===item.name.toLowerCase()&&(!item.color||x.color?.toLowerCase()===item.color.toLowerCase())&&(!item.format||x.format?.toLowerCase()===item.format.toLowerCase());const index=allItems.findIndex(x=>x.id===item.id);const allocated=allItems.slice(0,index<0?0:index).filter(compatible).filter(x=>!["Acheté","Commandé","J’en ai déjà"].includes(x.status)).reduce((n,x)=>n+x.quantity,0);const fromInventory=Math.max(0,inventoryUsed(item,inventory)-allocated);return Math.max(0,item.quantity-(item.owned||0)-fromInventory)}
export function optimize(state:AppState,strategy:Strategy,avoidStoreCost=10):PlanLine[]{const choices:PlanLine[]=state.items.flatMap(item=>{const needed=missing(item,state.inventory,state.items);if(!needed)return[];return state.prices.filter(p=>p.itemId===item.id&&p.available&&p.verifiedAt&&p.matchStatus!=="candidate"&&p.matchStatus!=="rejected"&&state.selectedMerchants.includes(p.merchantId)&&(!item.mandatoryMerchant||p.merchantId===item.mandatoryMerchant)).map(p=>({item,merchantId:p.merchantId,needed,packages:Math.ceil(needed/p.packageQuantity),cost:Math.ceil(needed/p.packageQuantity)*p.packagePrice}))});const neededIds=new Set(state.items.filter(x=>missing(x,state.inventory,state.items)>0).map(x=>x.id)),active=state.selectedMerchants,plans:{lines:PlanLine[];score:number}[]=[];for(let mask=1;mask<(1<<active.length);mask++){const allowed=new Set(active.filter((_,i)=>mask&(1<<i))),lines=cheapest(choices.filter(x=>allowed.has(x.merchantId)));if(lines.length!==neededIds.size)continue;const stores=new Set(lines.map(x=>x.merchantId)).size,items=lines.reduce((n,x)=>n+x.cost,0),fees=shippingTotal(lines,state),discount=couponDiscount(lines,state)+promotionDiscount(lines,state),penalty=strategy==="few"?stores*avoidStoreCost*4:strategy==="balanced"?stores*avoidStoreCost:0;plans.push({lines,score:items+fees-discount+penalty})}return plans.sort((a,b)=>a.score-b.score)[0]?.lines||[]}
function cheapest(choices:PlanLine[]){const by=new Map<string,PlanLine>();choices.forEach(c=>{const old=by.get(c.item.id);if(!old||c.cost<old.cost)by.set(c.item.id,c)});return [...by.values()]}
export function couponDiscount(lines:PlanLine[],state:AppState){return state.coupon.active&&lines.some(x=>x.merchantId==="commande-scolaire")?Math.min(state.coupon.value,lines.filter(x=>x.merchantId==="commande-scolaire").reduce((n,x)=>n+x.cost,0)):0}
export function promotionDiscount(lines:PlanLine[],state:AppState){return (state.promotions||[]).filter(p=>p.active&&p.code&&p.value>0).reduce((total,p)=>{const subtotal=lines.filter(x=>x.merchantId===p.merchantId).reduce((n,x)=>n+x.cost,0);const discount=p.kind==="percent"?subtotal*Math.min(p.value,100)/100:p.value;return total+Math.min(discount,subtotal)},0)}
export function fulfillmentOption(lines:PlanLine[],state:AppState,merchantId:MerchantId){const s=(state.merchantSettings||[]).find(x=>x.merchantId===merchantId),subtotal=lines.filter(x=>x.merchantId===merchantId).reduce((n,x)=>n+x.cost,0);if(!s)return{mode:"shop" as const,label:"Magasinage en personne",cost:0};const raw=s.mode==="online"?"delivery":s.mode==="store"?"shop":s.mode,delivery=s.freeShippingThreshold&&subtotal>=s.freeShippingThreshold?0:s.shippingFee,pickup=s.pickupFee||0,options=[{mode:"delivery" as const,label:"Livraison à domicile",cost:delivery},{mode:"pickup" as const,label:"Ramassage en magasin",cost:pickup},{mode:"shop" as const,label:"Magasinage en personne",cost:0}];return raw==="auto"?options.sort((a,b)=>a.cost-b.cost)[0]:options.find(x=>x.mode===raw)||options[2]}
export function shippingTotal(lines:PlanLine[],state:AppState){return [...new Set(lines.map(x=>x.merchantId))].reduce((total,id)=>total+fulfillmentOption(lines,state,id).cost,0)}
