import {AppState,MerchantId,Supply} from "./types";
const item=(id:string,level:Supply["level"],quantity:number,name:string,color?:string,format?:string,requirements?:string):Supply=>({id,level,quantity,name,color,format,requirements,status:"À acheter"});
export const merchants:{id:MerchantId;name:string;color:string}[]=[{id:"jean-coutu",name:"Jean Coutu",color:"#e83e4d"},{id:"bureau-en-gros",name:"Bureau en Gros",color:"#d71920"},{id:"commande-scolaire",name:"Commande Scolaire",color:"#2463a7"}];
export const seedItems:Supply[]=[
 item("2-cah-b", "2e année",2,"Cahier ½ interligné","bleu","23,2 × 18,1 cm","Format et réglure obligatoires"),item("2-cah-v","2e année",2,"Cahier ½ interligné","vert","23,2 × 18,1 cm","Format et réglure obligatoires"),item("2-duo-b","2e année",2,"Duo-tang","bleu"),item("2-duo-r","2e année",2,"Duo-tang","rouge"),item("2-duo-v","2e année",2,"Duo-tang","vert"),item("2-hb","2e année",12,"Crayon de plomb HB"),item("2-colle","2e année",2,"Bâton de colle","","40 g"),item("2-eff","2e année",2,"Efface blanche"),item("2-color","2e année",1,"Crayons de couleur","","boîte de 24"),item("2-case","2e année",1,"Étui à crayons"),
 item("4-cah","4e année",4,"Cahier ligné","","27,6 × 21,3 cm","Réglure 0,7 cm obligatoire"),item("4-hb","4e année",24,"Crayon de plomb HB"),item("4-pocket","4e année",1,"Pochette translucide","","format lettre","Bouton-pression obligatoire"),item("4-duo-b","4e année",3,"Duo-tang","bleu"),item("4-duo-r","4e année",3,"Duo-tang","rouge"),item("4-duo-v","4e année",2,"Duo-tang","vert"),item("4-glue","4e année",2,"Bâton de colle","","40 g"),item("4-marker","4e année",2,"Surligneur"),item("4-rule","4e année",1,"Règle métrique","","30 cm"),
 item("6-cah","6e année",8,"Cahier ligné","","27,6 × 21,3 cm","Réglure 0,7 cm obligatoire"),item("6-grid","6e année",2,"Cahier quadrillé","","27,6 × 21,3 cm","Quadrillage 0,5 cm obligatoire"),item("6-duo-b","6e année",3,"Duo-tang","bleu"),item("6-duo-r","6e année",2,"Duo-tang","rouge"),item("6-duo-v","6e année",2,"Duo-tang","vert"),item("6-hb","6e année",24,"Crayon de plomb HB"),item("6-pen","6e année",4,"Stylo","bleu"),item("6-binder","6e année",1,"Cartable à anneaux","","1½ po"),item("6-ex","6e année",1,"Cahier d’exercices avec ISBN","","ISBN à confirmer","Édition obligatoire")
];
seedItems.find(x=>x.id==="6-ex")!.mandatoryMerchant="commande-scolaire";
const priceFor=(x:Supply,m:MerchantId,i:number)=>({itemId:x.id,merchantId:m,packagePrice:Number((1.19+(i%7)*.72+(m==="commande-scolaire"?.35:m==="bureau-en-gros"?.1:0)).toFixed(2)),packageQuantity:x.name.includes("Crayon de plomb")?12:1,available:true});
export const initialState:AppState={items:seedItems,inventory:[{id:"inv1",name:"Crayon de plomb HB",quantity:18},{id:"inv2",name:"Duo-tang",color:"bleu",quantity:3},{id:"inv3",name:"Bâton de colle",format:"40 g",quantity:1}],prices:seedItems.flatMap((x,i)=>merchants.map(m=>priceFor(x,m.id,i))),selectedMerchants:merchants.map(x=>x.id),coupon:{active:true,value:10},plan:[],history:[]};
